import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import net from 'node:net';

async function freePort(){return await new Promise((resolve,reject)=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p))});s.on('error',reject)})}
async function waitFor(url,timeout=12000){const until=Date.now()+timeout;let last;while(Date.now()<until){try{const r=await fetch(url);if(r.ok)return r}catch(e){last=e}await new Promise(r=>setTimeout(r,120))}throw last||new Error('server timeout')}
let proc,base;
test.before(async()=>{const port=await freePort();base=`http://127.0.0.1:${port}`;proc=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),HOST:'127.0.0.1',ALPHALENS_TEST_MODE:'1',CATALOG_SYNC_ON_START:'false',SSE_HEARTBEAT_MS:'1000',QUOTE_POLL_MS:'1200',JWT_SECRET:'integration-test-secret-at-least-32-chars',DATA_FILE:`/tmp/alphalens-data-${port}.json`,CATALOG_FILE:`/tmp/alphalens-catalog-${port}.json`},stdio:['ignore','pipe','pipe']});await waitFor(`${base}/api/health`)});
test.after(async()=>{if(proc&&!proc.killed){proc.kill('SIGTERM');await new Promise(resolve=>{proc.once('exit',resolve);setTimeout(resolve,2000)})}});

test('health, version and page are available',async()=>{const h=await (await fetch(`${base}/api/health`)).json();assert.equal(h.ok,true);assert.equal((await (await fetch(`${base}/api/version`)).json()).version,'15.1.0');const page=await (await fetch(base)).text();assert.match(page,/AlphaLens Enterprise v15\.1/)});
test('snapshot returns complete test-mode data',async()=>{const d=await (await fetch(`${base}/api/snapshot?market=US&symbol=AAPL`)).json();assert.equal(d.quote.symbol,'AAPL');assert.ok(d.fundamentals.total>=0);assert.ok(d.profile.description);assert.ok(d.profile.sources.length);assert.ok(d.news.length);assert.equal(d.quality.partial,true);assert.ok(d.quality.errors.length)});
test('search and history APIs work without external network',async()=>{const rows=await (await fetch(`${base}/api/search?market=US&q=AAPL`)).json();assert.equal(rows[0].symbol,'AAPL');const h=await (await fetch(`${base}/api/history?market=US&symbol=AAPL&range=1M`)).json();assert.ok(h.rows.length>=50)});
test('AI endpoint returns a structured research signal',async()=>{const snapshot=await (await fetch(`${base}/api/snapshot?market=US&symbol=AAPL`)).json();const d=await (await fetch(`${base}/api/ai/analyze`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fundamentals:snapshot.fundamentals,quote:snapshot.quote,news:snapshot.news,profile:snapshot.profile})})).json();assert.ok(['買入','持有','賣出'].includes(d.signal));assert.ok(Array.isArray(d.oneMinuteSummary));assert.ok(Array.isArray(d.riskRadar));assert.ok(Array.isArray(d.evidence));assert.ok(Array.isArray(d.upgradeConditions))});

test('financial trends endpoint returns structured quarterly data',async()=>{const d=await (await fetch(`${base}/api/financial-trends?market=US&symbol=AAPL`)).json();assert.ok(Array.isArray(d.quarterly));assert.ok(d.quarterly.length>=8);assert.ok(Number.isFinite(d.coverage));assert.ok(d.source)});
test('SSE stream stays alive with ready, ping and quote events',async()=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),6000);const r=await fetch(`${base}/api/live?market=US&symbol=AAPL`,{signal:controller.signal});assert.equal(r.headers.get('content-type').startsWith('text/event-stream'),true);const reader=r.body.getReader(),decoder=new TextDecoder();let text='';try{while(!(/event: ready/.test(text)&&/event: ping/.test(text)&&/event: quote/.test(text))){const {value,done}=await reader.read();if(done)break;text+=decoder.decode(value,{stream:true})}}finally{clearTimeout(timer);controller.abort()}assert.match(text,/event: ready/);assert.match(text,/event: ping/);assert.match(text,/event: quote/)});

test('concurrent snapshots and rankings remain responsive',async()=>{const started=Date.now();const snapshots=await Promise.all(Array.from({length:20},()=>fetch(`${base}/api/snapshot?market=US&symbol=AAPL`).then(r=>r.json())));assert.equal(snapshots.every(x=>x.quote?.symbol==='AAPL'),true);const rankings=await Promise.all(['gainers','volume','hot'].map(type=>fetch(`${base}/api/ranking?market=US&type=${type}`).then(r=>r.json())));assert.equal(rankings.every(x=>Array.isArray(x.rows)&&x.rows.length>0),true);assert.ok(Date.now()-started<5000,`stress request took ${Date.now()-started}ms`)});
test('system status exposes provider health without crashing',async()=>{const d=await (await fetch(`${base}/api/system/status`)).json();assert.equal(d.version,'15.1.0');assert.ok(Array.isArray(d.providers));assert.ok(Number.isFinite(d.uptimeSeconds))});
test('auth registration and login work',async()=>{const email=`test-${Date.now()}@example.com`,password='password123';let r=await fetch(`${base}/api/auth/register`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Tester',email,password})});assert.equal(r.ok,true);const reg=await r.json();assert.ok(reg.token);r=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});assert.equal(r.ok,true);const login=await r.json();assert.ok(login.token)});
